### ISSUE TITLE
failed to ssh with debian as password

### ISSUE THREAD

**Issue by mizzi0n** [minimum2scp/dockerfiles#228] opened 2017-03-01 15:17 UTC
i  pulled a copy of the image, its running and accepting ssh login attemps but said password is incorrect when i use debian. this is for the baseimage docker

**Comment by minimum2scp** [comment] 2017-03-01 22:59
I cannot reproduce it.

```
tsuyoshi@mira% docker run --name test -d minimum2scp/baseimage:latest
7e6c2d49c3804621ad29cdc4030ef3169f35d316b60be319c5787f12fac07677
tsuyoshi@mira% docker inspect -f '{{ .NetworkSettings.IPAddress }}' test
172.17.0.3
tsuyoshi@mira% ping 172.17.0.3
PING 172.17.0.3 (172.17.0.3) 56(84) bytes of data.
64 bytes from 172.17.0.3: icmp_seq=1 ttl=64 time=0.040 ms
^C
--- 172.17.0.3 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.040/0.040/0.040/0.000 ms
tsuyoshi@mira% ssh debian@172.17.0.3
Warning: Permanently added '172.17.0.3' (ECDSA) to the list of known hosts.
debian@172.17.0.3's password:                                                  # <-- enter "debian"
Linux 7e6c2d49c380 4.9.0-2-amd64 #1 SMP Debian 4.9.13-1 (2017-02-27) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
debian@7e6c2d49c380:~$ 
```

Please show your system configuration (OS, docker version, etc), and steps to reproduce.

**Comment by minimum2scp** [comment] 2017-06-01 17:06
@mizzi0n 
Please show your system configuration (OS, docker-engine, docker-machine, etc), and steps to reproduce.
If you don't respond to this message, I will close this issue.

**Closed** 2017-06-21 15:53 UTC
